return {
  {
    "mfussenegger/nvim-lint",
    opts = {
      linters_by_ft = {
        clojure = { "clj-kondo" },
        cmakefile = { "cmakelint" },
        cpp = { "clangtidy", "cppcheck", "cpplint", "flawfinder" },
        css = { "stylelint" },
        dotenv = { "dotenv_linter" },
        elixir = { "credo" },
        dockerfile = { "hadolint", "trivy" },
        haskell = { "hlint" },
        go = { "golangcilint", "revive" },
        java = { "checkstyle" },
        javascript = { "biomejs", "eslint", "jshint", "standardjs" },
        json = { "jsonlint" },
        jsx = { "biomejs" },
        kotlin = { "ktlint" },
        latex = { "chktex", "lacheck" },
        markdown = { "markdownlint", "vale" },
        nix = { "nix", "statix" },
        perl = { "checkpatch", "perlcritic", "perlimports" },
        php = { "php", "phpcs", "phpinsights", "phpmd", "phpstan", "psalm" },
        proto = { "buf_lint" },
        python = { "bandit", "flake8", "mypy", "pycodestyle", "pydocstyle", "pylint", "ruff", "vulture" },
        ruby = { "ruby", "rubocop", "standardrb" },
        shell = { "shellcheck" },
        sql = { "sqlfluff" },
        typescript = { "biomejs" },
        yaml = { "yamllint" },
        zsh = { "zsh" },
      },
    },
  },
}
